services:
  s3:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - 7000:9000
      - 7070:9090
    command: >-
      server /data
      --console-address ":9090"
      --address ":9000"
    volumes:
      - minio_data:/data
    
  db:
    image: postgres:17.5-bookworm
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_DATA=/var/lib/postgresql/data
    networks:
      - gotravix
    volumes:
      - pg_data:/var/lib/postgresql/data
      - 

  gotravix-api-base:
    image: gotravix-api:stable
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - gotravix
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - APP_ORIGIN=${APP_ORIGIN}
      - APP_PORT=${APP_PORT:-3000}
      - JWT_SECRET=${JWT_SECRET:-myjwtsecret}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-myjwtrefreshsecret}
      - DATABASE_URL=${DATABASE_URL}
      - SMTP_HOST=${SMTP_HOST}      
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM:-ernestom@brakusa.com}

    command: "npm run start"
  
  gotravix-api-sidecar:
    extends:
      service: gotravix-api-base
    command: "npm run migrate"
  
  gotravix-api:
    extends:
      service: gotravix-api-base
    depends_on:
      - gotravix-api-sidecar
    command: "npm run start"
      
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    depends_on:
      - gotravix-api
    networks:
      - gotravix
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: |
      trap exit TERM
      DOMAIN=brakusa.com
      EMAIL=admin@brakusa.com
      CERT_PATH="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
      while :; do
        if [ ! -f "$CERT_PATH" ]; then
          certbot certonly \
            --webroot \
            -w /var/www/certbot \
            -d $DOMAIN \
            --email $EMAIL \
            --agree-tos \
            --no-eff-email \
            --non-interactive
        else
          certbot renew --webroot -w /var/www/certbot
        fi
        sleep 72h & wait $!
      done

    networks:
      - gotravix
    

volumes:
  pg_data:
    driver: local
  pgadmin_data:
    driver: local
  minio_data:
    driver: local

networks:
  gotravix:
