services:
  db:
    image: postgres:17.5-bookworm
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=gotravix
      - POSTGRES_PASSWORD=testing123
      - POSTGRES_DB_DATA=/var/lib/postgresql/data
    networks:
      - gotravix

  gotravix-api:
    image: gotravix-api:latest
    ports:
      - 3000:3000
    networks:
      - gotravix

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    depends_on:
      - gotravix-api
    networks:
      - gotravix
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: |
      trap exit TERM
      DOMAIN=brakusa.com
      EMAIL=admin@brakusa.com
      CERT_PATH="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
      while :; do
        if [ ! -f "$CERT_PATH" ]; then
          certbot certonly \
            --webroot \
            -w /var/www/certbot \
            -d $DOMAIN \
            --email $EMAIL \
            --agree-tos \
            --no-eff-email \
            --non-interactive
        else
          certbot renew --webroot -w /var/www/certbot
        fi
        sleep 72h & wait $!
      done

    networks:
      - gotravix
    

volumes:
  pgadmin_data:
    driver: local

networks:
  gotravix:
