name: "Build, Test, and Deploy"

on:
  push:
    branches:
      # - main
      - arturo_dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      - name: Get repo name
        run: |
          echo "REPO_NAME=$(basename ${{github.repository}})" >> $GITHUB_ENV
      - name: Fetch changes, build and deploy
        env:
          VPS_KEY: "${{secrets.VPS_KEY}}"
          VPS_USER: "${{secrets.VPS_USER}}"
          VPS_HOST: "${{secrets.VPS_HOST}}"
        run: |
          echo  "${VPS_KEY}" > private.key && chmod 600 private.key;
          ssh -i private.key -o StrictHostKeyChecking=no "${VPS_USER}"@"${VPS_HOST}" <<END
            rm -rf "$REPO_NAME";
            git clone --branch ${{github.ref_name}} --depth 1 "${{github.server_url}}/${{github.repository}}.git";
            cd "$REPO_NAME";
            git checkout "${{github.ref_name}}";
            echo "Dropping old containers ...";
            sudo docker-compose -f docker/docker-compose-prod.yml down gotravix-api db-migrator --remove-orphans;
            echo "Rebuilding and deploying containers ...";
            sudo docker-compose --env-file ../env/${REPO_NAME}/.env -f docker/docker-compose-prod.yml up -d --build gotravix-api;
          END


        shell: bash
    





